### ISSUE TITLE
Nodes on testnet doesn't accept reservations

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tfexplorer#186]
![Screenshot from 2020-10-11 13-23-13](https://user-images.githubusercontent.com/10658229/95677801-54dbfc80-0bc8-11eb-83d5-a6d3ec585637.png)

It waits until deployment timeouts (15 mins)

example wid: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/490477

- 72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib

**Comment by LeeSmet** [comment]
seems provisiond panics, and is stuck in a restart loop. Relevant logs:

```
...
  | 2020-10-12 11:11:21 | [+] provisiond: 2020-10-12T09:11:21Z info starting provision module broker=unix:///var/run/redis.sock
-- | -- | --
  |   | 2020-10-12 11:11:21 | [+] provisiond: 2020-10-12T09:11:21Z info restart detected, keep reservation cache intact
  |   | 2020-10-12 11:11:21 | [+] flistd: 2020-10-12T09:11:21Z debug running cleaner job
  |   | 2020-10-12 11:11:18 | [-] provisiond: 	/home/runner/work/zos/zos/cmds/provisiond/main.go:164 +0xff0
  |   | 2020-10-12 11:11:18 | [-] provisiond: main.main()
  |   | 2020-10-12 11:11:18 | [-] provisiond: 	/home/runner/work/zos/zos/pkg/provision/engine.go:138 +0xbd1
  |   | 2020-10-12 11:11:18 | [-] provisiond: github.com/threefoldtech/zos/pkg/provision.(*Engine).Run(0xc000406000, 0x1088360, 0xc00003a800, 0x0, 0x0)
  |   | 2020-10-12 11:11:18 | [-] provisiond: 	/home/runner/work/zos/zos/pkg/provision/engine.go:205 +0x174
  |   | 2020-10-12 11:11:18 | [-] provisiond: github.com/threefoldtech/zos/pkg/provision.(*Engine).provision(0xc000406000, 0x1088360, 0xc00003a800, 0xc00058cf00, 0x0, 0xc0005d3c00)
  |   | 2020-10-12 11:11:18 | [-] provisiond: 	/home/runner/work/zos/zos/pkg/provision/primitives/container.go:109
  |   | 2020-10-12 11:11:18 | [-] provisiond: github.com/threefoldtech/zos/pkg/provision/primitives.(*Provisioner).containerProvision(...)
  |   | 2020-10-12 11:11:18 | [-] provisiond: 	/home/runner/work/zos/zos/pkg/provision/primitives/container.go:172 +0xa1d
  |   | 2020-10-12 11:11:18 | [-] provisiond: github.com/threefoldtech/zos/pkg/provision/primitives.(*Provisioner).containerProvisionImpl(0xc00079e960, 0x1088360, 0xc00003a800, 0xc00058cf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  |   | 2020-10-12 11:11:18 | [-] provisiond: 	/home/runner/work/zos/zos/pkg/provision/primitives/crypto.go:39 +0x345
  |   | 2020-10-12 11:11:18 | [-] provisiond: github.com/threefoldtech/zos/pkg/provision/primitives.decryptSecret(0xc0005e0000, 0xa0, 0xc0004d6028, 0x3, 0x1, 0x1073060, 0xc00000e030, 0x8, 0x4, 0x0, ...)
  |   | 2020-10-12 11:11:18 | [-] provisiond: 	/home/runner/work/zos/zos/pkg/stubs/identity_stub.go:45 +0x355
  |   | 2020-10-12 11:11:18 | [-] provisiond: github.com/threefoldtech/zos/pkg/stubs.(*IdentityManagerStub).DecryptECDH(0xc000352948, 0xc0005680a0, 0x50, 0xa0, 0xc0006af6c0, 0x20, 0x40, 0x0, 0x0, 0x4760bc, ...)
  |   | 2020-10-12 11:11:18 | [-] provisiond: goroutine 1 [running]:
  |   | 2020-10-12 11:11:18 | [-] provisiond:
  |   | 2020-10-12 11:11:18 | [-] provisiond: panic: not a function
  |   | 2020-10-12 11:11:18 | [+] networkd: 2020-10-12T09:11:18Z info check if interface has a cable plugged in iface=b-NFFfnKSqqFxDm
  |   | 2020-10-12 11:11:18 | [+] networkd: 2020-10-12T09:11:18Z info check if interface has a cable plugged in iface=b-G6i28tC2UBNyU
  |   | 2020-10-12 11:11:18 | [+] networkd: 2020-10-12T09:11:18Z info interface is not plugged in, skipping interface=b-HiB2BGoT9Pqzn
  |   | 2020-10-12 11:11:13 | [+] networkd: 2020-10-12T09:11:13Z info check if interface has a cable plugged in iface=b-HiB2BGoT9Pqzn
  |   | 2020-10-12 11:11:13 | [+] networkd: 2020-10-12T09:11:13Z info check if interface has a cable plugged in iface=b-EmszGGwsUacmE
  |   | 2020-10-12 11:11:13 | [+] networkd: 2020-10-12T09:11:13Z info interface is not plugged in, skipping interface=b-Ha467CygvG52h
  |   | 2020-10-12 11:11:10 | [+] provisiond: 2020-10-12T09:11:10Z info start provisioning reservation duration=2562047h47m16.854775807s expired=false id=490520-1 tag= to-delete=false type=container
  |   | 2020-10-12 11:11:10 | [+] provisiond: 2020-10-12T09:11:10Z info provision statistics container=21 cru=26 delegateDomain=0 hru=5130 k8sVM=4 mru=31 network=169 proxy=0 reverseProxy=0 sru=221 subdomain=0 volume=15 zDBNamespace=12
  |   | 2020-10-12 11:11:10 | [+] provisiond: 2020-10-12T09:11:10Z info reservation have already been processed id=476445-1
  |   | 2020-10-12 11:11:10 | [+] provisiond: 2020-10-12T09:11:10Z info start provisioning reservation duration=2562047h47m16.854775807s expired=false id=476445-1 tag= to-delete=false type=container
  |   | 2020-10-12 11:11:10 | [+] provisiond: 2020-10-12T09:11:10Z info reservation have already been processed id=472733-6
  |   | 2020-10-12 11:11:10 | [+] provisiond: 2020-10-12T09:11:10Z info start provisioning reservation duration=2562047h47m16.854775807s expired=false id=472733-6 tag= to-delete=false type=volume
  |   | 2020-10-12 11:11:10 | [+] provisiond: 2020-10-12T09:11:10Z info reservation have already been processed id=474441-1
  |   | 2020-10-12 11:11:10 | [+] provisiond: 2020-10-12T09:11:10Z info start provisioning reservation duration=2562047h47m16.854775807s expired=false id=474441-1 tag= to-delete=false type=volume
  |   | 2020-10-12 11:11:10 | [+] provisiond: 2020-10-12T09:11:10Z info reservation have already been processed id=472725-6
  |   | 2020-10-12 11:11:10 | [+] provisiond: 2020-10-12T09:11:10Z info start provisioning reservation duration=2562047h47m16.854775807s expired=false id=472725-6 tag= to-delete=false type=volume
...
```

**Comment by LeeSmet** [comment]
```
~ # identityd -v
Version: v0.4.0 @Revision: 60e0f395ce91eb018523b1abed1f5054356d5432 (dirty-repo)
```

**Comment by zaibon** [comment]
seems some manual update of identityd was made on this node. we manually fixed the problem
