### ISSUE TITLE
500 Server Error: could not set up capacity escrow: failed to get escrow address for customer: failed to create a new account for customer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#233]
While deploying a 3Bot on mainnet
```
Traceback (most recent call last):
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
  File "/root/js-sdk/jumpscale/sals/marketplace/apps_chatflow.py", line 453, in infrastructure_setup
    self._get_pool()
  File "/root/js-sdk/jumpscale/packages/threebot_deployer/chats/threebot.py", line 121, in _get_pool
    self.pool_info = deployer.create_3bot_pool(
  File "/root/js-sdk/jumpscale/sals/marketplace/deployer.py", line 325, in create_3bot_pool
    pool_info = j.sals.zos.get(identity_name).pools.create(
  File "/root/js-sdk/jumpscale/sals/zos/pools.py", line 63, in create
    return self._reserve(pool)
  File "/root/js-sdk/jumpscale/sals/zos/pools.py", line 24, in _reserve
    return self._pools.create(pool)
  File "/root/js-sdk/jumpscale/clients/explorer/pools.py", line 38, in create
    resp = self._session.post(self._base_url, json=pool.to_dict())
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/root/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
requests.exceptions.HTTPError: 500 Server Error: could not set up capacity escrow: failed to get escrow address for customer: failed to create a new account for customer 1340: failed to activate escrow account GB3H4BBWBG5VZFFOZ3TDK3OYGMDIZDAH2VHIOKBV6X4X4FGSROSNE4JN: horizon error: "Transaction Failed" - check horizon.Error.Problem for more information for url: https://explorer.grid.tf/api/v1/reservations/pools
```
another trial
```
Traceback (most recent call last):
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 147, in wrapper
    getattr(self, step_name)()
  File "/root/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 668, in wrapper
    return func(*args, **kwargs)
  File "/root/js-sdk/jumpscale/sals/marketplace/apps_chatflow.py", line 453, in infrastructure_setup
    self._get_pool()
  File "/root/js-sdk/jumpscale/packages/threebot_deployer/chats/threebot.py", line 121, in _get_pool
    self.pool_info = deployer.create_3bot_pool(
  File "/root/js-sdk/jumpscale/sals/marketplace/deployer.py", line 325, in create_3bot_pool
    pool_info = j.sals.zos.get(identity_name).pools.create(
  File "/root/js-sdk/jumpscale/sals/zos/pools.py", line 63, in create
    return self._reserve(pool)
  File "/root/js-sdk/jumpscale/sals/zos/pools.py", line 24, in _reserve
    return self._pools.create(pool)
  File "/root/js-sdk/jumpscale/clients/explorer/pools.py", line 38, in create
    resp = self._session.post(self._base_url, json=pool.to_dict())
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/root/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
requests.exceptions.HTTPError: 500 Server Error: could not set up capacity escrow: failed to get escrow address for customer: failed to create a new account for customer 1341: failed to activate escrow account GC4GOHDS7SB4NGQSTYTF2Z4O44SA3ZTW2VMOEU525X7QXCRXKFDQ4YPM: horizon error: "Transaction Failed" - check horizon.Error.Problem for more information for url: https://explorer.grid.tf/api/v1/reservations/pools
```

**Comment by DylanVerstraete** [comment]
Explorer production wallet was not funded with enough XLM anymore. Can be resolved by funding the explorer wallet again.

**Comment by DylanVerstraete** [comment]
Explorer wallet funded
