### ISSUE TITLE
Escrow only uses node collection to try to get the pools farm ID, not the gateway collection

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/tfexplorer#255]
- farm https://explorer.testnet.grid.tf/api/v1/farms/13677

```
JS-NG> j.sals.zos.get().pools.create(0, 0, 0, "csfarmer", ["TFT"])                                                                                                                                            
2020-12-24 15:40:46.723 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:25 - Request https://explorer.testnet.grid.tf/api/v1/farms?page=1 method: GET body: None headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '414', 'date': 'Thu, 24 Dec 2020 13:40:46 GMT', 'authorization': 'Signature keyId="414",algorithm="ed25519",signature="XqtY0A3jz7sgt1gmilCz8fGXS7XAeCBy4BcPmFcCVJGGiY/l4zr+Qs+oJuhbh7fSc/T52blw0/n4MW/VKXj3Ag==",created="1608817246",expires="1608817306",headers="(created) date threebot-id"'}
2020-12-24 15:40:46.833 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:25 - Request https://explorer.testnet.grid.tf/api/v1/nodes?farm=13677&page=1 method: GET body: None headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '414', 'date': 'Thu, 24 Dec 2020 13:40:46 GMT', 'authorization': 'Signature keyId="414",algorithm="ed25519",signature="XqtY0A3jz7sgt1gmilCz8fGXS7XAeCBy4BcPmFcCVJGGiY/l4zr+Qs+oJuhbh7fSc/T52blw0/n4MW/VKXj3Ag==",created="1608817246",expires="1608817306",headers="(created) date threebot-id"'}
2020-12-24 15:40:46.935 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:25 - Request https://explorer.testnet.grid.tf/api/v1/gateways?farm_id=13677&page=1 method: GET body: None headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '414', 'date': 'Thu, 24 Dec 2020 13:40:46 GMT', 'authorization': 'Signature keyId="414",algorithm="ed25519",signature="XqtY0A3jz7sgt1gmilCz8fGXS7XAeCBy4BcPmFcCVJGGiY/l4zr+Qs+oJuhbh7fSc/T52blw0/n4MW/VKXj3Ag==",created="1608817246",expires="1608817306",headers="(created) date threebot-id"'}
2020-12-24 15:40:47.055 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:25 - Request https://explorer.testnet.grid.tf/api/v1/reservations/pools method: POST body: b'{"json": "{\\"pool_id\\": 0, \\"cus\\": 0, \\"sus\\": 0, \\"ipv4us\\": 0, \\"node_ids\\": [\\"HGEF1wafew1mQEtpPPsVSG3isvLqjinTNT3vsG2y2UBA\\"], \\"currencies\\": [\\"TFT\\"]}", "data_reservation": {"pool_id": 0, "cus": 0, "sus": 0, "ipv4us": 0, "node_ids": ["HGEF1wafew1mQEtpPPsVSG3isvLqjinTNT3vsG2y2UBA"], "currencies": ["TFT"]}, "customer_tid": 414, "customer_signature": "93d81512e87434dbd07a6c23a6ce6d894b8fe6ff3ad10fb54603711d21457132d6e7e5556556da9e0c089a703ac711ce2c5d462b3cabcacc694f035c01df5905"}' headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '414', 'Content-Length': '489', 'content-type': 'application/json', 'date': 'Thu, 24 Dec 2020 13:40:46 GMT', 'authorization': 'Signature keyId="414",algorithm="ed25519",signature="XqtY0A3jz7sgt1gmilCz8fGXS7XAeCBy4BcPmFcCVJGGiY/l4zr+Qs+oJuhbh7fSc/T52blw0/n4MW/VKXj3Ag==",created="1608817246",expires="1608817306",headers="(created) date threebot-id"'}
2020-12-24 15:40:47.059 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:93 - requests.exceptions.HTTPError: 500 Server Error: could not set up capacity escrow: could not get node: mongo: no documents in result for url: https://explorer.testnet.grid.tf/api/v1/reservations/pools
Traceback (most recent call last):
  File "/home/waleed/js-sdk/.venv/bin/jsng", line 8, in <module>
    sys.exit(run())
    │   │    └ <Command run>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f263c040040>
           └ <Command run>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f263c56e6d0>
         │    └ <function Command.invoke at 0x7f263c0409d0>
         └ <Command run>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'command': None}
           │   │      │    │           └ <click.core.Context object at 0x7f263c56e6d0>
           │   │      │    └ <function run at 0x7f263b87f310>
           │   │      └ <Command run>
           │   └ <function Context.invoke at 0x7f263c03faf0>
           └ <click.core.Context object at 0x7f263c56e6d0>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'command': None}
           │         └ ()
           └ <function run at 0x7f263b87f310>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/jumpscale/entry_points/jsng.py", line 34, in run
    sys.exit(embed(globals(), locals(), configure=ptconfig, history_filename=HISTORY_FILENAME))
    │   │    │                                    │                          └ '/home/waleed/.jsng/history.txt'
    │   │    │                                    └ <function ptconfig at 0x7f263b56d040>
    │   │    └ <function embed at 0x7f263b3a70d0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/ptpython/repl.py", line 350, in embed
    repl.run()
    │    └ <function PythonRepl.run at 0x7f263b3a6c10>
    └ <ptpython.repl.PythonRepl object at 0x7f263b566850>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/ptpython/repl.py", line 74, in run
    self._process_text(text)
    │    │             └ 'j.sals.zos.get().pools.create(0, 0, 0, "csfarmer", ["TFT"])'
    │    └ <function PythonRepl._process_text at 0x7f263b3a6ca0>
    └ <ptpython.repl.PythonRepl object at 0x7f263b566850>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/ptpython/repl.py", line 88, in _process_text
    self._handle_exception(e)
    │    │                 └ HTTPError('500 Server Error: could not set up capacity escrow: could not get node: mongo: no documents in result for url: htt...
    │    └ functools.partial(<function patched_handle_exception at 0x7f263b87f8b0>, <ptpython.repl.PythonRepl object at 0x7f263b566850>)
    └ <ptpython.repl.PythonRepl object at 0x7f263b566850>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/ptpython/repl.py", line 163, in _execute
    six.exec_(code, self.get_globals(), self.get_locals())
    │   │     │     │    │              │    └ <function embed.<locals>.get_locals at 0x7f263b3a7160>
    │   │     │     │    │              └ <ptpython.repl.PythonRepl object at 0x7f263b566850>
    │   │     │     │    └ <function embed.<locals>.get_globals at 0x7f263b87f5e0>
    │   │     │     └ <ptpython.repl.PythonRepl object at 0x7f263b566850>
    │   │     └ <code object <module> at 0x7f262f5e2c90, file "<stdin>", line 1>
    │   └ <built-in function exec>
    └ <module 'six' from '/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/six.py'>
> File "<stdin>", line 1, in <module>

  File "/home/waleed/js-sdk/jumpscale/sals/zos/pools.py", line 65, in create
    return self._reserve(pool)
           │    │        └ PoolCreate(
           │    │            json='{"pool_id": 0, "cus": 0, "sus": 0, "ipv4us": 0, "node_ids": ["HGEF1wafew1mQEtpPPsVSG3isvLqjinTNT3vsG2y2UB...
           │    └ <function Pools._reserve at 0x7f26353ce790>
           └ <jumpscale.sals.zos.pools.Pools object at 0x7f26345b75e0>

  File "/home/waleed/js-sdk/jumpscale/sals/zos/pools.py", line 24, in _reserve
    return self._pools.create(pool)
           │    │      │      └ PoolCreate(
           │    │      │          json='{"pool_id": 0, "cus": 0, "sus": 0, "ipv4us": 0, "node_ids": ["HGEF1wafew1mQEtpPPsVSG3isvLqjinTNT3vsG2y2UB...
           │    │      └ <function Pools.create at 0x7f26377ef4c0>
           │    └ <jumpscale.clients.explorer.pools.Pools object at 0x7f2635243370>
           └ <jumpscale.sals.zos.pools.Pools object at 0x7f26345b75e0>

  File "/home/waleed/js-sdk/jumpscale/clients/explorer/pools.py", line 38, in create
    resp = self._session.post(self._base_url, json=pool.to_dict())
           │    │        │    │    │               │    └ <function Base._get_data at 0x7f2639ff2790>
           │    │        │    │    │               └ PoolCreate(
           │    │        │    │    │                   json='{"pool_id": 0, "cus": 0, "sus": 0, "ipv4us": 0, "node_ids": ["HGEF1wafew1mQEtpPPsVSG3isvLqjinTNT3vsG2y2UB...
           │    │        │    │    └ <property object at 0x7f26377a3400>
           │    │        │    └ <jumpscale.clients.explorer.pools.Pools object at 0x7f2635243370>
           │    │        └ <function Session.post at 0x7f2639a94d30>
           │    └ <requests.sessions.Session object at 0x7f2635241ac0>
           └ <jumpscale.clients.explorer.pools.Pools object at 0x7f2635243370>

  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
           │    │               │    │    │     │    │       └ {}
           │    │               │    │    │     │    └ {'json': '{"pool_id": 0, "cus": 0, "sus": 0, "ipv4us": 0, "node_ids": ["HGEF1wafew1mQEtpPPsVSG3isvLqjinTNT3vsG2y2UBA"], "curr...
           │    │               │    │    │     └ {'json': '{"pool_id": 0, "cus": 0, "sus": 0, "ipv4us": 0, "node_ids": ["HGEF1wafew1mQEtpPPsVSG3isvLqjinTNT3vsG2y2UBA"], "curr...
           │    │               │    │    └ None
           │    │               │    └ None
           │    │               └ 'https://explorer.testnet.grid.tf/api/v1/reservations/pools'
           │    └ <function Session.request at 0x7f2639a94af0>
           └ <requests.sessions.Session object at 0x7f2635241ac0>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [POST]>
           │    └ <function Session.send at 0x7f2639a94f70>
           └ <requests.sessions.Session object at 0x7f2635241ac0>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
    │   │                         │      │    └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
    │   │                         │      └ <Response [500]>
    │   │                         └ {'response': [<function log_request at 0x7f26378d6550>, <function raise_for_status at 0x7f263789baf0>]}
    │   └ <function dispatch_hook at 0x7f2639ae5dc0>
    └ <Response [500]>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
    │            │    │            └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
    │            │    └ <Response [500]>
    │            └ <function raise_for_status at 0x7f263789baf0>
    └ None

  File "/home/waleed/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
          │         │                        └ <Response [500]>
          │         └ '500 Server Error: could not set up capacity escrow: could not get node: mongo: no documents in result for url: https://explo...
          └ <class 'requests.exceptions.HTTPError'>

requests.exceptions.HTTPError: 500 Server Error: could not set up capacity escrow: could not get node: mongo: no documents in result for url: https://explorer.testnet.grid.tf/api/v1/reservations/pools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/waleed/js-sdk/jumpscale/sals/zos/pools.py", line 65, in create
    return self._reserve(pool)
           │             └ PoolCreate(
  json='{"pool_id": 0, "cus": 0, "sus": 0, "ipv4us": 0, "node_ids": ["HGEF1wafew1mQEtpPPsVSG3isvLqjinTNT3vsG2y2UBA"]...
           └ <jumpscale.sals.zos.pools.Pools object at 0x7f26345b75e0>
  File "/home/waleed/js-sdk/jumpscale/sals/zos/pools.py", line 24, in _reserve
    return self._pools.create(pool)
           │                  └ PoolCreate(
  json='{"pool_id": 0, "cus": 0, "sus": 0, "ipv4us": 0, "node_ids": ["HGEF1wafew1mQEtpPPsVSG3isvLqjinTNT3vsG2y2UBA"]...
           └ <jumpscale.sals.zos.pools.Pools object at 0x7f26345b75e0>
  File "/home/waleed/js-sdk/jumpscale/clients/explorer/pools.py", line 38, in create
    resp = self._session.post(self._base_url, json=pool.to_dict())
           │                  │                    └ PoolCreate(
  json='{"pool_id": 0, "cus": 0, "sus": 0, "ipv4us": 0, "node_ids": ["HGEF1wafew1mQEtpPPsVSG3isvLqjinTNT3vsG2y2UBA"]...
           │                  └ <jumpscale.clients.explorer.pools.Pools object at 0x7f2635243370>
           └ <jumpscale.clients.explorer.pools.Pools object at 0x7f2635243370>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
           │                    │         │          │       └ {}
           │                    │         │          └ {'json': '{"pool_id": 0, "cus": 0, "sus": 0, "ipv4us": 0, "node_ids": ["HGEF1wafew1mQEtpPPsVSG3isvLqjinTNT3vsG2y2UBA"], "currenc...
           │                    │         └ None
           │                    └ 'https://explorer.testnet.grid.tf/api/v1/reservations/pools'
           └ <requests.sessions.Session object at 0x7f2635241ac0>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
           │         │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │         └ <PreparedRequest [POST]>
           └ <requests.sessions.Session object at 0x7f2635241ac0>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
    │   │                         │      │    └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
    │   │                         │      └ <Response [500]>
    │   │                         └ {'response': [<function log_request at 0x7f26378d6550>, <function raise_for_status at 0x7f263789baf0>]}
    │   └ <function dispatch_hook at 0x7f2639ae5dc0>
    └ <Response [500]>
  File "/home/waleed/js-sdk/.venv/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
    │            │    │            └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
    │            │    └ <Response [500]>
    │            └ <function raise_for_status at 0x7f263789baf0>
    └ None
  File "/home/waleed/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
          │         │                        └ <Response [500]>
          │         └ '500 Server Error: could not set up capacity escrow: could not get node: mongo: no documents in result for url: https://explorer...
          └ <class 'requests.exceptions.HTTPError'>
requests.exceptions.HTTPError: 500 Server Error: could not set up capacity escrow: could not get node: mongo: no documents in result for url: https://explorer.testnet.grid.tf/api/v1/reservations/pools

500 Server Error: could not set up capacity escrow: could not get node: mongo: no documents in result for url: https://explorer.testnet.grid.tf/api/v1/reservations/pools
JS-NG>  
```

It's working on devnet
- https://explorer.devnet.grid.tf/api/v1/farms/15
```
JS-NG> j.sals.zos.get("devnet").pools.create(0, 0, 0, "csfarmer", ["TFT"])                                                                                                                                    
2020-12-24 15:41:58.663 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:25 - Request https://explorer.devnet.grid.tf/api/v1/farms?page=1 method: GET body: None headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '27', 'date': 'Thu, 24 Dec 2020 13:41:58 GMT', 'authorization': 'Signature keyId="27",algorithm="ed25519",signature="iAJIvCWxitY672J0GpznAvZN9GnqXu/aofeTYzIlckaxyOaR5PK9k6/Q5r/giRqf5O5heo8uXaIfLd8M24SwDg==",created="1608817318",expires="1608817378",headers="(created) date threebot-id"'}
2020-12-24 15:41:58.782 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:25 - Request https://explorer.devnet.grid.tf/api/v1/nodes?farm=15&page=1 method: GET body: None headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '27', 'date': 'Thu, 24 Dec 2020 13:41:58 GMT', 'authorization': 'Signature keyId="27",algorithm="ed25519",signature="iAJIvCWxitY672J0GpznAvZN9GnqXu/aofeTYzIlckaxyOaR5PK9k6/Q5r/giRqf5O5heo8uXaIfLd8M24SwDg==",created="1608817318",expires="1608817378",headers="(created) date threebot-id"'}
2020-12-24 15:41:58.888 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:25 - Request https://explorer.devnet.grid.tf/api/v1/gateways?farm_id=15&page=1 method: GET body: None headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '27', 'date': 'Thu, 24 Dec 2020 13:41:58 GMT', 'authorization': 'Signature keyId="27",algorithm="ed25519",signature="iAJIvCWxitY672J0GpznAvZN9GnqXu/aofeTYzIlckaxyOaR5PK9k6/Q5r/giRqf5O5heo8uXaIfLd8M24SwDg==",created="1608817318",expires="1608817378",headers="(created) date threebot-id"'}
2020-12-24 15:41:59.005 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:25 - Request https://explorer.devnet.grid.tf/api/v1/reservations/pools method: POST body: b'{"json": "{\\"pool_id\\": 0, \\"cus\\": 0, \\"sus\\": 0, \\"ipv4us\\": 0, \\"node_ids\\": [\\"9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2\\"], \\"currencies\\": [\\"TFT\\"]}", "data_reservation": {"pool_id": 0, "cus": 0, "sus": 0, "ipv4us": 0, "node_ids": ["9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2"], "currencies": ["TFT"]}, "customer_tid": 27, "customer_signature": "d13bf90731b63e8c16c289a8a85306ef10b69d55191be0420c6640422d8623851b46a564782c290ae953c6fcf48ed473552e27e01f60c34804fbd274b8747606"}' headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '27', 'Content-Length': '488', 'content-type': 'application/json', 'date': 'Thu, 24 Dec 2020 13:41:58 GMT', 'authorization': 'Signature keyId="27",algorithm="ed25519",signature="iAJIvCWxitY672J0GpznAvZN9GnqXu/aofeTYzIlckaxyOaR5PK9k6/Q5r/giRqf5O5heo8uXaIfLd8M24SwDg==",created="1608817318",expires="1608817378",headers="(created) date threebot-id"'}
PoolCreated(
  reservation_id=1763,
  escrow_information=PoolEscrow(
  address='',
  asset='',
  amount=0
)
)
```

**Comment by LeeSmet** [comment]
You are creating pools with non existing node ids. This works on devnet because the error is triggered by the escrow, which is disabled on devnet.

If anything, the error 500 should be changed to an error 400, somewhat related to https://github.com/threefoldtech/tfexplorer/issues/55

**Comment by xmonader** [comment]
@LeeSmet the farm already has nodes (meant for gateways usage only) 
![image](https://user-images.githubusercontent.com/64129/103093748-ef62ae00-4603-11eb-9cb6-695ca00e98e8.png)

nodeid: HGEF1wafew1mQEtpPPsVSG3isvLqjinTNT3vsG2y2UBA

**Comment by LeeSmet** [comment]
hhm right I see. The same logic holds, but we only check in the node collection in the escrow, not the gateway collection

**Comment by xmonader** [comment]
FYI, when added a dummy node to the farm and brought it down, I managed to create pools.

**Comment by LeeSmet** [comment]
Fixed in code, explorers still need to be updated

**Comment by LeeSmet** [comment]
Code is live on testnet and devnet

**Comment by xmonader** [comment]
verified
