### ISSUE TITLE
pools taking too long to extend cus, ip4us 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#263]
I did the payment but the requested units never reflect in the pools

## pools

- https://explorer.devnet.grid.tf/api/v1/reservations/pools/2499
- https://explorer.devnet.grid.tf/api/v1/reservations/pools/2503
```
cs6s1AA==",created="1609519282",expires="1609519342",headers="(created) date threebot-id"'}
2021-01-01 16:41:22.320 | INFO     | jumpscale.sals.vdc.deployer:_log:768 - VDC: 96b31312b5c949a48dd7132c4e
de2933 NAME: nowwhatttt: OWNER: ahmedthabet searching for available public ip in farm lochristi_dev_lab
2021-01-01 16:41:22.321 | INFO     | jumpscale.servers.gedis.server:_on_connection:270 - Executing method f
etch from actor chatflows_chatbot to client ('127.0.0.1', 55646)
127.0.0.1 - - [2021-01-01 16:41:22] "POST /chatflows/chatbot/fetch HTTP/1.0" 200 556 0.006703
2021-01-01 16:41:22.435 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:26 - Request https://e
xplorer.devnet.grid.tf/api/v1/farms?page=1 method: GET body: None headers: {'user-agent': 'python-requests/
2.24.0', 'accept-encoding': 'gzip, deflate', 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '2
583', 'date': 'Fri, 01 Jan 2021 16:41:22 GMT', 'authorization': 'Signature keyId="2583",algorithm="ed25519"
,signature="3zb/1wPp2pOxkIXvu3ItbEWgpz31fsaXqGyQy8ZrRKdP8Op92jEhqrzQEpN0yZ/h4YVMZokUjf2tyDYcs6s1AA==",creat
ed="1609519282",expires="1609519342",headers="(created) date threebot-id"'}
2021-01-01 16:41:22.441 | INFO     | jumpscale.sals.vdc.deployer:_log:768 - VDC: 96b31312b5c949a48dd7132c4e
de2933 NAME: nowwhatttt: OWNER: ahmedthabet attempting to reserve public ip: 185.69.167.133/24 on farm: loc
hristi_dev_lab pool: 2499 node: 2anfZwrzskXiUHPLTqH1veJAia8G6rW2eFLy5YFMa1MP
2021-01-01 16:41:22.564 | DEBUG    | jumpscale.clients.explorer.explorer:log_request:26 - Request https://e
xplorer.devnet.grid.tf/api/v1/reservations/workloads method: POST body: b'{"id": 0, "ipaddress": "185.69.16
7.133/24", "workload_id": 1, "node_id": "2anfZwrzskXiUHPLTqH1veJAia8G6rW2eFLy5YFMa1MP", "pool_id": 2499, "d
escription": "{\\"vdc_uuid\\": \\"96b31312b5c949a48dd7132c4ede2933\\"}", "reference": "", "customer_tid": 2
583, "customer_signature": "4711040a065806d24e19d177e6ed50a43c402a80bd0c206d70f73ff792aee9435e425704daf83c9
34320237fc842fa689813cddd7cc065d0fd283002699a600e", "next_action": 3, "signatures_provision": [], "signing_
request_provision": {"signers": [], "quorum_min": 0}, "signing_request_delete": {"signers": [2583], "quorum
_min": 1}, "signatures_farmer": [], "signatures_delete": [], "epoch": 1609519282, "metadata": "1mTH|dmg^tgs
nwQvjc;!_(%#HZ_b-@pW4wauM@VhDJ_gZ58AyR*$9Rw2v@Ed0auEoh6(1!2CaI#v?Tlwr?{*njrLbRXS$PCp5uMYN*~xlZL;T$$kGe!+y",
 "workload_type": 11}' headers: {'user-agent': 'python-requests/2.24.0', 'accept-encoding': 'gzip, deflate'
, 'accept': '*/*', 'connection': 'keep-alive', 'threebot-id': '2583', 'Content-Length': '799', 'content-typ
e': 'application/json', 'date': 'Fri, 01 Jan 2021 16:41:22 GMT', 'authorization': 'Signature keyId="2583",a
lgorithm="ed25519",signature="3zb/1wPp2pOxkIXvu3ItbEWgpz31fsaXqGyQy8ZrRKdP8Op92jEhqrzQEpN0yZ/h4YVMZokUjf2ty
DYcs6s1AA==",created="1609519282",expires="1609519342",headers="(created) date threebot-id"'}
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/root/js-sdk/jumpscale/sals/vdc/deployer.py", line 363, in deploy_vdc_kubernetes
    master_pool_id, gs, master_size, cluster_secret, [self.ssh_key.public_key.strip()], self.vdc_uuid, nv
  File "/root/js-sdk/jumpscale/sals/vdc/kubernetes.py", line 169, in deploy_master
    pool_id, master_node.node_id, solution_uuid=solution_uuid
  File "/root/js-sdk/jumpscale/sals/vdc/public_ip.py", line 43, in get_public_ip
    solution_uuid=solution_uuid,
  File "/root/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 1201, in deploy_public_ip
      return zos.workloads.deploy(public_ip)
  File "/root/js-sdk/jumpscale/sals/zos/workloads.py", line 157, in deploy
    return self._workloads.create(workload)
  File "/root/js-sdk/jumpscale/clients/explorer/workloads.py", line 95, in create
    resp = self._session.post(url, json=data)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/requests/sessio
ns.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/requests/sessio
ns.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/requests/sessio
ns.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/requests/hooks.
py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/root/js-sdk/jumpscale/clients/explorer/errors.py", line 23, in raise_for_status
    raise HTTPError(http_error_msg, response=resp)
requests.exceptions.HTTPError: 402 Client Error: pool needs additional capacity to support this workload fo
r url: https://explorer.devnet.grid.tf/api/v1/reservations/workloads
2021-01-01T16:41:22Z <Greenlet at 0x7f2b42a42848: <bound method VDCDeployer.deploy_vdc_kubernetes of <jumps
cale.sals.vdc.deployer.VDCDeployer object at 0x7f2b42ae6940>>('lochristi_dev_lab', <jumpscale.sals.vdc.sche
duler.GlobalScheduler obje, '020f2fd48bcd3d46a74d12d43919f0e1')> failed with HTTPError

2021-01-01 16:41:22.572 | ERROR    | jumpscale.sals.vdc.deployer:_log:768 - VDC: 96b31312b5c949a48dd7132c4e
de2933 NAME: nowwhatttt: OWNER: ahmedthabet failed to deploy VDC. cancelling workloads with uuid 96b31312b5
c949a48dd7132c4ede2933
  
```

**Comment by muhamadazmy** [comment]
By checking the pools payment info, it seems the payment has been refunded. The cause of the refund is unknown atm so I updated both devnet and testnet with a version that tracks the cause of the cancellation on the payment info. So when this happen again we will have more info to track down the problem

**Comment by muhamadazmy** [comment]
I will put it in verification until it happens again.

**Comment by xmonader** [comment]
After the new API
After sucessfull payment
![image](https://user-images.githubusercontent.com/64129/103704135-72dfb000-4fb1-11eb-80ac-70c6befce6ab.png)

the pool still after 10 mins not reflecting the resources

![image](https://user-images.githubusercontent.com/64129/103704040-45930200-4fb1-11eb-8585-69197934fd8b.png)


https://explorer.devnet.grid.tf/api/v1/reservations/pools/2672
https://explorer.devnet.grid.tf/api/v1/reservations/pools/payment/2672

**Comment by LeeSmet** [comment]
The new capacity not being added is actually correct given the reservation state. `paid` essentially means that the escrow has received sufficient funds for the reservation, and will attempt to do the payout to the farmer, after which the capacity is added to the pool. If this is successful, the `released` flag will be set. If it fails, the escrow will attempt to refund the client. In that case the `canceled` flag will be set. If the escrow fails due to insufficient funds before it expires, the client will also be refunded and the `canceled` flag set in the same way. Given that neither of these flags are currently set, even after this amount of time has elapsed, it seems that the escrow is somehow hanging.

**Comment by xmonader** [comment]
also been happening to frequent now 
https://explorer.devnet.grid.tf/api/v1/reservations/pools/payment/2698
https://explorer.devnet.grid.tf/api/v1/reservations/pools/2698

Seems the explorer getting timeouts from stellar accroding to @muhamadazmy logs
![image](https://user-images.githubusercontent.com/64129/103758896-86276580-501b-11eb-9d41-3c7c00b60b8f.png)

**Comment by muhamadazmy** [comment]
Please confirm if this still an issue ?

**Comment by muhamadazmy** [comment]
Please re-create a new issue if this still happens
